name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-gql-server-lambda:
    name: Deploy GQL Server Lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      # use bun to build the lambda
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: build lambda
        run: npx turbo run server#build:lambda
      - name: serverless deploy
        run: npx serverless deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          LOCALITIES_API_URL: ${{ secrets.LOCALITIES_API_URL }}
          LOCALITIES_API_KEY: ${{ secrets.LOCALITIES_API_KEY }}
          LOCALITIES_API_STAGE: ${{ vars.LOCALITIES_API_STAGE }}
          AUTH_ISSUER: ${{ vars.AUTH_ISSUER }}
          AUTH_AUDIENCE: ${{ vars.AUTH_AUDIENCE }}
          AUTH_JWT_SECRET: ${{ secrets.AUTH_JWT_SECRET }}
