name: Test

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        env:
          LOCALITIES_API_URL: ${{ secrets.LOCALITIES_API_URL }}
          LOCALITIES_API_KEY: ${{ secrets.LOCALITIES_API_KEY }}
          LOCALITIES_API_STAGE: ${{ vars.LOCALITIES_API_STAGE }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          AUTH_JWT_SECRET: ${{ secrets.AUTH_JWT_SECRET }}
          AUTH_DUMMY_USERNAME: ${{ secrets.AUTH_DUMMY_USERNAME }}
          AUTH_DUMMY_PASSWORD: ${{ secrets.AUTH_DUMMY_PASSWORD }}
          AUTH_ISSUER: ${{ vars.AUTH_ISSUER }}
          AUTH_AUDIENCE: ${{ vars.AUTH_AUDIENCE }}
